### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#35]
Started up our new 0.17 modded server and tried to run the script, crash on first run, very quickly:
```python
╰─➤  python auto.py --verbosegame OverGreg3 OverGreg3-0
OverGreg3
OverGreg3-0
factorio path: /mnt/storage0/overminddl1/Games/Factorio/factorio_0.17.16/bin/x64/factorio
output folder: script-output/FactorioMaps/OverGreg3
downloading https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.css
downloading https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet-src.min.js
downloading https://cdn.jsdelivr.net/npm/leaflet.fullscreen@1.4.5/Control.FullScreen.css
downloading https://cdn.jsdelivr.net/npm/leaflet.fullscreen@1.4.5/Control.FullScreen.min.js
downloading https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js
downloading https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css
downloading https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
downloading https://cdn.jsdelivr.net/gh/L0laapk3/Leaflet.OpacityControls@1/Control.Opacity.css
downloading https://cdn.jsdelivr.net/gh/L0laapk3/Leaflet.OpacityControls@1/Control.Opacity.js
downloading https://factorio.com/static/img/favicon.ico
downloading https://i.factoriomaps.com/t92kw.png
enabling FactorioMaps mod
cleaning up  
building autorun.lua                                                                                                                                                                                          
starting factorio                                                                                                                                                                                             
ln: missing file operand
Try 'ln --help' for more information.
Traceback (most recent call last):
  File "auto.py", line 376, in auto
    linkDir(os.path.join(tmpDir, "script-output"), "../../script-output")
  File "auto.py", line 252, in linkDir
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, shell=True)
  File "/home/overminddl1/.asdf/installs/python/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('ln', '-s', '/tmp/FactorioMaps-319988162/script-output', '/mnt/storage0/overminddl1/Games/Factorio/factorio_0.17.16/script-output')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto.py", line 629, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 604, in auto
    kill(pid)
UnboundLocalError: local variable 'pid' referenced before assignment
```

Two things, first is that absolutely no symlink should be getting created to to my `/tmp` partition, especially nothing as massive as FactorioMaps as the tmp partition is waaaaaay too small for something as huge as that (that is why I have it generating on an external drive directly as it is, the `/mnt/storage0` bit), and second, something like this should absolutely not be touching anything outside of the factorio directory without explicit consent.

**Comment by OvermindDL1** [comment]
For note, commenting all that symlink stuff out has the game loading at least.  That exceptionally should not be there...

**Comment by OvermindDL1** [comment]
The issue is the symlink is symlinking the paths backwards, simple fix.  ^.^
