### ISSUE TITLE
Config.ini categories aren't explicitly made

### ISSUE THREAD

**Issue by lordfiSh** [L0laapk3/FactorioMaps#58]
```
C:\Users\user\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_3.5.5>python auto.py --verbose
('--verbose',)
No save name passed. Using most recent save: game
factorio path: C:\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
output folder: script-output\FactorioMaps\game
checking for updates
enabling FactorioMaps mod
cleaning up
building autorun.lua
fm.autorun = {
HD = false,
day = true,
night = true,
alt_mode = true,
tags = true,
around_tag_range = 5.2,
around_build_range = 5.2,
around_connect_range = 1.2,
connect_types = {"lamp", "electric-pole", "radar", "straight-rail", "curved-rail", "rail-signal", "rail-chain-signal", "locomotive", "cargo-wagon", "fluid-wagon", "car"},
date = "07/02/20",
surfaces = nil,
name = "game/",
mapInfo = {},
chunkCache = {},
}
building config.ini
disabling FactorioMaps mod
cleaning up
Traceback (most recent call last):
  File "auto.py", line 802, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 491, in auto
    config["interface"]["show-tips-and-tricks"] = "false"
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'interface'
```

**Comment by L0laapk3** [comment]
Hi, thanks for reporting.
I'll fix it soon, in the meantime you can work around this by hiding the tips and tricks in your game when you load any save.

**Comment by lordfiSh** [comment]
Thanks. This is running headless on a Server, I look have to change it there...

**Comment by L0laapk3** [comment]
It won't work with factorio's headless build, this is an inherent
limitation of factorio. Otherwise, just copy your normal config.ini to your
server :)
