### ISSUE TITLE
Cannot run auto.py

### ISSUE THREAD

**Issue by LukasRepos** [L0laapk3/FactorioMaps#67]
When I do `python3 auto.py`, it gives me this error

```
Traceback (most recent call last):
  File "auto.py", line 44, in <module>
    from zoom import zoom, zoomRenderboxes
  File "C:\Users\Escola\AppData\Roaming\Factorio\mods\FactorioMaps-master\zoom.py", line 43, in <module>
    jpeg = TurboJPEG("mozjpeg/turbojpeg.dll")
  File "C:\Users\Escola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Impossível localizar o módulo especificado
```

**Comment by L0laapk3** [comment]
Assuming you are running `<python3> auto.py` from the folder directly and not `<python3 path/to/auto.py`, Is it possible that your antivirus deleted the mozjpeg/turbojpeg.dll file somehow? it appears to be missing.
