### ISSUE TITLE
Render failing when using WhistleStopFactories

### ISSUE THREAD

**Issue by billbo99** [L0laapk3/FactorioMaps#81]
I got this error trying to render a map

```
Traceback (most recent call last):
  File "auto.py", line 841, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 745, in auto
    rawPath = rawTags[tag["iconType"] + tag["iconName"][0].upper() + tag["iconName"][1:]]
  File "<string>", line 2, in __getitem__
  File "C:\Python37\lib\multiprocessing\managers.py", line 834, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'itemAdvanced-oil-processing-big_tagicon'
```

**Comment by billbo99** [comment]
https://cdn.discordapp.com/attachments/731572389615501345/732729134765179042/july_04.zip

save file here

**Comment by L0laapk3** [comment]
it appears that time has solved this bug
