### ISSUE TITLE
Unrecognized output from factorio

### ISSUE THREAD

**Issue by pablowilson** [L0laapk3/FactorioMaps#94]
Trying to run the script for the first time, getting an error: 
`Exception: Unrecognised output from factorio (maybe your version is outdated or too new?)

Output from factorio:
   0.000 Error Main.cpp:562: Error: Specified config file doesn't exist.`

I'm currently running on the current experimental 1.1.x, but I feel like that shouldn't be a problem for the error it's producing, can anyone confirm? Thanks.

Full output:
`me$ python3 auto.py --no-altmode --dayonly --hd --no-tags --steam --factorio=/mnt/d/Steam/steamapps/common/Factorio/bin/x64/factorio.exe
checking for updates
No save name passed. Using most recent save: The_Mountain
factorio path: /mnt/d/Steam/steamapps/common/Factorio/bin/x64/factorio.exe
output folder: script-output/FactorioMaps/The_Mountain
Enabling FactorioMaps mod
cleaning up
Building autorun.lua
Building config.ini
starting factorio
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "auto.py", line 164, in startGameAndReadGameLogs
    printingStackTraceback = handleGameLine(line, isFirstLine)
  File "auto.py", line 82, in handleGameLine
    raise Exception("Unrecognised output from factorio (maybe your version is outdated or too new?)\n\nOutput from factorio:\n" + line)
Exception: Unrecognised output from factorio (maybe your version is outdated or too new?)

Output from factorio:
   0.000 Error Main.cpp:562: Error: Specified config file doesn't exist.
`

**Comment by L0laapk3** [comment]
Sorry, I must have missed your issue. What did you do to get this issue? I was able to run the mod just fine on these versions. Are you using WSL to run this? (Since I see an exe path but in /mnt/d/). It can be just ran on windows.
The mod makes a temporary folder with a place for a custom factorio config, I assume something went wrong with creating the temporary folder.
